// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbcSPUaVtfQqeCoG0mAzfoKS0Loonxou4',
    appId: '1:1099213389115:web:4b2962d3f3137b9dd24b1e',
    messagingSenderId: '1099213389115',
    projectId: 'fir-flutter-codelab-9fe3e',
    authDomain: 'fir-flutter-codelab-9fe3e.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-9fe3e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDin-S7SQ3a1nidzXDZW_dDxKmCaDHH-Io',
    appId: '1:1099213389115:android:073bdf225d1f0071d24b1e',
    messagingSenderId: '1099213389115',
    projectId: 'fir-flutter-codelab-9fe3e',
    storageBucket: 'fir-flutter-codelab-9fe3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6KVh5q435Eoupiur36kNg5O1mY-JAlsU',
    appId: '1:1099213389115:ios:961b47715991f974d24b1e',
    messagingSenderId: '1099213389115',
    projectId: 'fir-flutter-codelab-9fe3e',
    storageBucket: 'fir-flutter-codelab-9fe3e.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6KVh5q435Eoupiur36kNg5O1mY-JAlsU',
    appId: '1:1099213389115:ios:60251bb575762c90d24b1e',
    messagingSenderId: '1099213389115',
    projectId: 'fir-flutter-codelab-9fe3e',
    storageBucket: 'fir-flutter-codelab-9fe3e.appspot.com',
    iosBundleId: 'com.example.gtkFlutter.RunnerTests',
  );
}
